-- Demo Inventory Data
-- This migration adds sample inventory items for testing

-- Insert sample inventory items
INSERT INTO inventory_items (
    name,
    description,
    sku,
    barcode,
    category_id,
    supplier_id,
    manufacturer,
    model,
    part_number,
    quantity,
    min_quantity,
    max_quantity,
    unit_cost,
    unit_price,
    location,
    shelf_location,
    condition,
    warranty_period,
    weight,
    dimensions,
    tags
) VALUES
-- Generators
(
    'Generac 22KW Guardian Series',
    '22kW air-cooled home standby generator with automatic transfer switch',
    'GEN-22K-001',
    '1234567890123',
    (SELECT id FROM inventory_categories WHERE name = 'Generators'),
    (SELECT id FROM suppliers WHERE name = 'Generac Power Systems'),
    'Generac',
    'Guardian Series 22KW',
    'G0070430',
    5,
    2,
    10,
    4500.00,
    5500.00,
    'Warehouse A',
    'A1-B2-C3',
    'new',
    60,
    450.5,
    '60 x 30 x 30 cm',
    ARRAY['generator', 'standby', 'automatic']
),
(
    'Generac 16KW Guardian Series',
    '16kW air-cooled home standby generator',
    'GEN-16K-001',
    '9876543210987',
    (SELECT id FROM inventory_categories WHERE name = 'Generators'),
    (SELECT id FROM suppliers WHERE name = 'Generac Power Systems'),
    'Generac',
    'Guardian Series 16KW',
    'G0070420',
    3,
    2,
    8,
    3800.00,
    4700.00,
    'Warehouse A',
    'A1-B2-C4',
    'new',
    60,
    380.0,
    '55 x 28 x 28 cm',
    ARRAY['generator', 'standby']
),
(
    'Cummins 20KW QuietConnect',
    '20kW liquid-cooled standby generator with sound enclosure',
    'CUM-20K-001',
    '4567891234567',
    (SELECT id FROM inventory_categories WHERE name = 'Generators'),
    (SELECT id FROM suppliers WHERE name = 'Cummins Power Generation'),
    'Cummins',
    'QuietConnect 20KW',
    'QC20',
    2,
    1,
    5,
    6500.00,
    7800.00,
    'Warehouse B',
    'B1-C2-D3',
    'new',
    84,
    650.0,
    '70 x 35 x 35 cm',
    ARRAY['generator', 'liquid-cooled', 'quiet']
),

-- Parts
(
    'Starter Motor - Generac',
    'Electric starter motor for Generac generators',
    'PAR-STR-001',
    '7891234567890',
    (SELECT id FROM inventory_categories WHERE name = 'Parts'),
    (SELECT id FROM suppliers WHERE name = 'Generac Power Systems'),
    'Generac',
    'Starter Motor',
    '0J8361',
    15,
    5,
    25,
    120.00,
    180.00,
    'Warehouse C',
    'C1-D2-E3',
    'new',
    24,
    8.5,
    '15 x 12 x 10 cm',
    ARRAY['starter', 'motor', 'generac']
),
(
    'Battery - 12V Deep Cycle',
    '12V deep cycle battery for generator systems',
    'PAR-BAT-001',
    '3216549870123',
    (SELECT id FROM inventory_categories WHERE name = 'Parts'),
    (SELECT id FROM suppliers WHERE name = 'Grainger Industrial Supply'),
    'Interstate',
    'Deep Cycle 12V',
    'DCM0035',
    25,
    10,
    50,
    85.00,
    125.00,
    'Warehouse C',
    'C1-D2-E4',
    'new',
    12,
    25.0,
    '30 x 17 x 20 cm',
    ARRAY['battery', '12v', 'deep-cycle']
),
(
    'Transfer Switch - 200A',
    '200A automatic transfer switch for residential use',
    'PAR-TRS-001',
    '6543210987654',
    (SELECT id FROM inventory_categories WHERE name = 'Parts'),
    (SELECT id FROM suppliers WHERE name = 'Generac Power Systems'),
    'Generac',
    '200A Transfer Switch',
    'RTSW200A3',
    8,
    3,
    15,
    450.00,
    650.00,
    'Warehouse C',
    'C1-D3-E1',
    'new',
    60,
    45.0,
    '40 x 25 x 15 cm',
    ARRAY['transfer-switch', 'automatic', '200a']
),

-- Tools
(
    'Multimeter - Fluke 117',
    'Digital multimeter for electrical testing',
    'TOL-MMT-001',
    '1472583690123',
    (SELECT id FROM inventory_categories WHERE name = 'Tools'),
    (SELECT id FROM suppliers WHERE name = 'Grainger Industrial Supply'),
    'Fluke',
    '117',
    'FLUKE-117',
    12,
    3,
    20,
    180.00,
    250.00,
    'Tool Room',
    'TR-A1-B1',
    'new',
    24,
    0.3,
    '8 x 4 x 2 cm',
    ARRAY['multimeter', 'electrical', 'testing']
),
(
    'Crimping Tool Set',
    'Professional wire crimping tool set',
    'TOL-CRP-001',
    '2583691470123',
    (SELECT id FROM inventory_categories WHERE name = 'Tools'),
    (SELECT id FROM suppliers WHERE name = 'Fastenal Company'),
    'Klein Tools',
    'Crimping Set',
    'KT-CRIMP-001',
    8,
    2,
    12,
    45.00,
    65.00,
    'Tool Room',
    'TR-A1-B2',
    'new',
    12,
    1.2,
    '25 x 15 x 5 cm',
    ARRAY['crimping', 'wire', 'electrical']
),

-- Supplies
(
    'Wire - 10 AWG THHN',
    '10 AWG THHN copper wire, 500ft spool',
    'SUP-WIR-001',
    '3692581470123',
    (SELECT id FROM inventory_categories WHERE name = 'Supplies'),
    (SELECT id FROM suppliers WHERE name = 'Grainger Industrial Supply'),
    'Southwire',
    'THHN 10 AWG',
    'SW-10THHN-500',
    20,
    5,
    30,
    85.00,
    120.00,
    'Warehouse D',
    'D1-E2-F1',
    'new',
    0,
    15.0,
    '30 x 30 x 10 cm',
    ARRAY['wire', 'copper', 'electrical']
),
(
    'Circuit Breaker - 30A',
    '30A circuit breaker for electrical panels',
    'SUP-CBR-001',
    '9638527410123',
    (SELECT id FROM inventory_categories WHERE name = 'Supplies'),
    (SELECT id FROM suppliers WHERE name = 'Fastenal Company'),
    'Square D',
    '30A Breaker',
    'SQD-30A-001',
    50,
    15,
    100,
    12.00,
    18.00,
    'Warehouse D',
    'D1-E2-F2',
    'new',
    12,
    0.2,
    '8 x 3 x 2 cm',
    ARRAY['circuit-breaker', 'electrical']
),

-- Electronics
(
    'Control Board - Generac',
    'Main control board for Generac generators',
    'ELE-CTL-001',
    '8529637410123',
    (SELECT id FROM inventory_categories WHERE name = 'Electronics'),
    (SELECT id FROM suppliers WHERE name = 'Generac Power Systems'),
    'Generac',
    'Control Board',
    '0J8361',
    6,
    2,
    10,
    350.00,
    500.00,
    'Warehouse E',
    'E1-F2-G1',
    'new',
    24,
    0.8,
    '20 x 15 x 3 cm',
    ARRAY['control-board', 'electronics', 'generac']
),

-- Safety Equipment
(
    'Safety Glasses - Clear',
    'ANSI Z87.1 certified safety glasses',
    'SAF-GLS-001',
    '7418529630123',
    (SELECT id FROM inventory_categories WHERE name = 'Safety Equipment'),
    (SELECT id FROM suppliers WHERE name = 'Grainger Industrial Supply'),
    '3M',
    'Safety Glasses',
    '3M-SG-CLEAR',
    100,
    25,
    200,
    8.50,
    12.00,
    'Safety Storage',
    'SS-A1-B1',
    'new',
    0,
    0.05,
    '15 x 8 x 3 cm',
    ARRAY['safety', 'glasses', 'ansi']
),
(
    'Hard Hat - Yellow',
    'ANSI Z89.1 certified hard hat',
    'SAF-HAT-001',
    '1597534860123',
    (SELECT id FROM inventory_categories WHERE name = 'Safety Equipment'),
    (SELECT id FROM suppliers WHERE name = 'Fastenal Company'),
    'MSA',
    'Hard Hat Yellow',
    'MSA-HH-YELLOW',
    25,
    8,
    40,
    15.00,
    22.00,
    'Safety Storage',
    'SS-A1-B2',
    'new',
    60,
    0.4,
    '25 x 20 x 15 cm',
    ARRAY['hard-hat', 'safety', 'ansi']
);

-- Insert some stock movements for demo
INSERT INTO stock_movements (
    item_id,
    movement_type,
    quantity,
    previous_quantity,
    new_quantity,
    reference_type,
    notes,
    unit_cost,
    total_value,
    created_by
) VALUES
-- Initial stock in
(
    (SELECT id FROM inventory_items WHERE sku = 'GEN-22K-001'),
    'in',
    5,
    0,
    5,
    'purchase_order',
    'Initial stock received',
    4500.00,
    22500.00,
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1)
),
(
    (SELECT id FROM inventory_items WHERE sku = 'GEN-16K-001'),
    'in',
    3,
    0,
    3,
    'purchase_order',
    'Initial stock received',
    3800.00,
    11400.00,
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1)
),
(
    (SELECT id FROM inventory_items WHERE sku = 'PAR-STR-001'),
    'in',
    15,
    0,
    15,
    'purchase_order',
    'Initial stock received',
    120.00,
    1800.00,
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1)
),
-- Some stock out
(
    (SELECT id FROM inventory_items WHERE sku = 'GEN-22K-001'),
    'out',
    1,
    5,
    4,
    'sales_order',
    'Sold to customer',
    4500.00,
    4500.00,
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1)
),
(
    (SELECT id FROM inventory_items WHERE sku = 'PAR-STR-001'),
    'out',
    2,
    15,
    13,
    'project',
    'Used in generator installation',
    120.00,
    240.00,
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1)
);

-- Insert some barcode scans for demo
INSERT INTO barcode_scans (
    barcode,
    item_id,
    scan_type,
    quantity,
    location,
    notes,
    scanned_by,
    device_info
) VALUES
(
    '1234567890123',
    (SELECT id FROM inventory_items WHERE barcode = '1234567890123'),
    'audit',
    5,
    'Warehouse A',
    'Initial inventory audit',
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1),
    '{"user_agent": "Mozilla/5.0", "timestamp": "2024-01-15T10:30:00Z"}'
),
(
    '9876543210987',
    (SELECT id FROM inventory_items WHERE barcode = '9876543210987'),
    'audit',
    3,
    'Warehouse A',
    'Initial inventory audit',
    (SELECT id FROM profiles WHERE role = 'admin' LIMIT 1),
    '{"user_agent": "Mozilla/5.0", "timestamp": "2024-01-15T10:35:00Z"}'
);

-- Insert some inventory alerts for demo
INSERT INTO inventory_alerts (
    item_id,
    alert_type,
    message,
    is_active,
    is_read
) VALUES
(
    (SELECT id FROM inventory_items WHERE sku = 'GEN-16K-001'),
    'low_stock',
    'Item Generac 16KW Guardian Series is running low on stock. Current quantity: 3, Minimum: 2',
    true,
    false
),
(
    (SELECT id FROM inventory_items WHERE sku = 'CUM-20K-001'),
    'low_stock',
    'Item Cummins 20KW QuietConnect is running low on stock. Current quantity: 2, Minimum: 1',
    true,
    false
); 